//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找已本地化的字符串等等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 Visual Studio 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找重写当前线程的 CurrentUICulture 
        /// 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 账号级别 的本地化字符串。
        /// </summary>
        internal static string accountlevel {
            get {
                return ResourceManager.GetString("accountlevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 账号管理归属 的本地化字符串。
        /// </summary>
        internal static string Account_managemen {
            get {
                return ResourceManager.GetString("Account_managemen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加 的本地化字符串。
        /// </summary>
        internal static string add {
            get {
                return ResourceManager.GetString("add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加人 的本地化字符串。
        /// </summary>
        internal static string added_by {
            get {
                return ResourceManager.GetString("added_by", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加时间 的本地化字符串。
        /// </summary>
        internal static string added_time {
            get {
                return ResourceManager.GetString("added_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 地址 的本地化字符串。
        /// </summary>
        internal static string address {
            get {
                return ResourceManager.GetString("address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加父模块 的本地化字符串。
        /// </summary>
        internal static string Add_parent_module {
            get {
                return ResourceManager.GetString("Add_parent_module", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加特定后台的特定人员使用 的本地化字符串。
        /// </summary>
        internal static string Add_specific_background_to_the_use_of_person {
            get {
                return ResourceManager.GetString("Add_specific_background_to_the_use_of_person", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加子模块 的本地化字符串。
        /// </summary>
        internal static string Add_sub_module {
            get {
                return ResourceManager.GetString("Add_sub_module", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 管理员 的本地化字符串。
        /// </summary>
        internal static string administrators {
            get {
                return ResourceManager.GetString("administrators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 管理员账号 的本地化字符串。
        /// </summary>
        internal static string Admin_acount {
            get {
                return ResourceManager.GetString("Admin_acount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 管理员部门 的本地化字符串。
        /// </summary>
        internal static string Admin_department {
            get {
                return ResourceManager.GetString("Admin_department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 管理员姓名 的本地化字符串。
        /// </summary>
        internal static string Admin_name {
            get {
                return ResourceManager.GetString("Admin_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户信息查询 的本地化字符串。
        /// </summary>
        internal static string advanced_search {
            get {
                return ResourceManager.GetString("advanced_search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全选 的本地化字符串。
        /// </summary>
        internal static string all {
            get {
                return ResourceManager.GetString("all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 所有部门 的本地化字符串。
        /// </summary>
        internal static string alldepartment {
            get {
                return ResourceManager.GetString("alldepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 所有平台 的本地化字符串。
        /// </summary>
        internal static string allplatform {
            get {
                return ResourceManager.GetString("allplatform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 所有角色 的本地化字符串。
        /// </summary>
        internal static string All_roles {
            get {
                return ResourceManager.GetString("All_roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 】已存在 的本地化字符串。
        /// </summary>
        internal static string Already_exist {
            get {
                return ResourceManager.GetString("Already_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 权限复制/转移 的本地化字符串。
        /// </summary>
        internal static string authority_copytransfer {
            get {
                return ResourceManager.GetString("authority_copytransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 权限系统 的本地化字符串。
        /// </summary>
        internal static string authority_management {
            get {
                return ResourceManager.GetString("authority_management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 为角色设置权限 的本地化字符串。
        /// </summary>
        internal static string authority_setting_for_different_roles {
            get {
                return ResourceManager.GetString("authority_setting_for_different_roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户基础信息查询 的本地化字符串。
        /// </summary>
        internal static string basic_search {
            get {
                return ResourceManager.GetString("basic_search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 所属游戏 的本地化字符串。
        /// </summary>
        internal static string Belong_to_the_game {
            get {
                return ResourceManager.GetString("Belong_to_the_game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BG后台 的本地化字符串。
        /// </summary>
        internal static string BG_background {
            get {
                return ResourceManager.GetString("BG_background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 绑定常用IP 的本地化字符串。
        /// </summary>
        internal static string BindingcommonlyusedIP {
            get {
                return ResourceManager.GetString("BindingcommonlyusedIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 渠道描述 的本地化字符串。
        /// </summary>
        internal static string channel_description {
            get {
                return ResourceManager.GetString("channel_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 渠道ID 的本地化字符串。
        /// </summary>
        internal static string channel_ID {
            get {
                return ResourceManager.GetString("channel_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 渠道信息修改失败 的本地化字符串。
        /// </summary>
        internal static string Channel_information_modification_failed {
            get {
                return ResourceManager.GetString("Channel_information_modification_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 渠道信息创建成功 的本地化字符串。
        /// </summary>
        internal static string Channel_information_to_create_success {
            get {
                return ResourceManager.GetString("Channel_information_to_create_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 渠道信息修改成功 的本地化字符串。
        /// </summary>
        internal static string Channel_information_to_modify_the_success_of {
            get {
                return ResourceManager.GetString("Channel_information_to_modify_the_success_of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 渠道名称 的本地化字符串。
        /// </summary>
        internal static string channel_name {
            get {
                return ResourceManager.GetString("channel_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 渠道设置 的本地化字符串。
        /// </summary>
        internal static string channel_setting {
            get {
                return ResourceManager.GetString("channel_setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 渠道ID【 的本地化字符串。
        /// </summary>
        internal static string Channe_lID {
            get {
                return ResourceManager.GetString("Channe_lID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 充值钻石 的本地化字符串。
        /// </summary>
        internal static string chargediamond {
            get {
                return ResourceManager.GetString("chargediamond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 玩家的充值记录 的本地化字符串。
        /// </summary>
        internal static string chargerecord {
            get {
                return ResourceManager.GetString("chargerecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 城市 的本地化字符串。
        /// </summary>
        internal static string city {
            get {
                return ResourceManager.GetString("city", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 北京有限公司 的本地化字符串。
        /// </summary>
        internal static string company_name {
            get {
                return ResourceManager.GetString("company_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 复制 的本地化字符串。
        /// </summary>
        internal static string copy {
            get {
                return ResourceManager.GetString("copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 被复制账号 的本地化字符串。
        /// </summary>
        internal static string copyaccount {
            get {
                return ResourceManager.GetString("copyaccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 复制权限 的本地化字符串。
        /// </summary>
        internal static string copy_authority {
            get {
                return ResourceManager.GetString("copy_authority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 国家 的本地化字符串。
        /// </summary>
        internal static string country {
            get {
                return ResourceManager.GetString("country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建游戏渠道 的本地化字符串。
        /// </summary>
        internal static string Create_a_game_channel {
            get {
                return ResourceManager.GetString("Create_a_game_channel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建渠道信息 的本地化字符串。
        /// </summary>
        internal static string Create_channel_information {
            get {
                return ResourceManager.GetString("Create_channel_information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建渠信息创建失败 的本地化字符串。
        /// </summary>
        internal static string Create_channel_information_creation_failed {
            get {
                return ResourceManager.GetString("Create_channel_information_creation_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建功能信息 的本地化字符串。
        /// </summary>
        internal static string Create_functional_information {
            get {
                return ResourceManager.GetString("Create_functional_information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建游戏信息 的本地化字符串。
        /// </summary>
        internal static string Create_game_information {
            get {
                return ResourceManager.GetString("Create_game_information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建游戏信息成功 的本地化字符串。
        /// </summary>
        internal static string Create_game_information_success {
            get {
                return ResourceManager.GetString("Create_game_information_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建总功能信息 的本地化字符串。
        /// </summary>
        internal static string Create_general_function_information {
            get {
                return ResourceManager.GetString("Create_general_function_information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建父模块 的本地化字符串。
        /// </summary>
        internal static string Create_parent_module {
            get {
                return ResourceManager.GetString("Create_parent_module", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建平台信息 的本地化字符串。
        /// </summary>
        internal static string Create_platform_information {
            get {
                return ResourceManager.GetString("Create_platform_information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建角色 的本地化字符串。
        /// </summary>
        internal static string Create_role {
            get {
                return ResourceManager.GetString("Create_role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建子模块 的本地化字符串。
        /// </summary>
        internal static string Create_sub_module {
            get {
                return ResourceManager.GetString("Create_sub_module", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建用户 的本地化字符串。
        /// </summary>
        internal static string Create_user {
            get {
                return ResourceManager.GetString("Create_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前登录情况 的本地化字符串。
        /// </summary>
        internal static string current_login_situation {
            get {
                return ResourceManager.GetString("current_login_situation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前版本 的本地化字符串。
        /// </summary>
        internal static string current_version {
            get {
                return ResourceManager.GetString("current_version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        internal static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除渠道 的本地化字符串。
        /// </summary>
        internal static string Delete_channel {
            get {
                return ResourceManager.GetString("Delete_channel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除功能 的本地化字符串。
        /// </summary>
        internal static string Delete_function {
            get {
                return ResourceManager.GetString("Delete_function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除游戏 的本地化字符串。
        /// </summary>
        internal static string Delete_game {
            get {
                return ResourceManager.GetString("Delete_game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除总功能 的本地化字符串。
        /// </summary>
        internal static string Delete_general_function {
            get {
                return ResourceManager.GetString("Delete_general_function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除平台 的本地化字符串。
        /// </summary>
        internal static string Delete_platform {
            get {
                return ResourceManager.GetString("Delete_platform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除角色 的本地化字符串。
        /// </summary>
        internal static string Delete_role {
            get {
                return ResourceManager.GetString("Delete_role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 解散房间 的本地化字符串。
        /// </summary>
        internal static string delroom {
            get {
                return ResourceManager.GetString("delroom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定 的本地化字符串。
        /// </summary>
        internal static string Determine {
            get {
                return ResourceManager.GetString("Determine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 钻石数量 的本地化字符串。
        /// </summary>
        internal static string diamondnum {
            get {
                return ResourceManager.GetString("diamondnum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 钻石充值失败 的本地化字符串。
        /// </summary>
        internal static string diamond_charge_fail {
            get {
                return ResourceManager.GetString("diamond_charge_fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 钻石充值成功 的本地化字符串。
        /// </summary>
        internal static string diamond_charge_suc {
            get {
                return ResourceManager.GetString("diamond_charge_suc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在树目录中显示 的本地化字符串。
        /// </summary>
        internal static string Display_in_the_tree_directory {
            get {
                return ResourceManager.GetString("Display_in_the_tree_directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否进行密码重置 的本地化字符串。
        /// </summary>
        internal static string Dopasswordreset {
            get {
                return ResourceManager.GetString("Dopasswordreset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 放弃上传 的本地化字符串。
        /// </summary>
        internal static string Drop_upload {
            get {
                return ResourceManager.GetString("Drop_upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑 的本地化字符串。
        /// </summary>
        internal static string edit {
            get {
                return ResourceManager.GetString("edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 邮箱 的本地化字符串。
        /// </summary>
        internal static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 结束时间 的本地化字符串。
        /// </summary>
        internal static string ending_time {
            get {
                return ResourceManager.GetString("ending_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 执行 的本地化字符串。
        /// </summary>
        internal static string execute {
            get {
                return ResourceManager.GetString("execute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出 的本地化字符串。
        /// </summary>
        internal static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出Excel 的本地化字符串。
        /// </summary>
        internal static string export_as_Excel {
            get {
                return ResourceManager.GetString("export_as_Excel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 失败 的本地化字符串。
        /// </summary>
        internal static string fail {
            get {
                return ResourceManager.GetString("fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 功能信息修改失败 的本地化字符串。
        /// </summary>
        internal static string Failure_of_functional_information_modification {
            get {
                return ResourceManager.GetString("Failure_of_functional_information_modification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 总功能信息修改失败 的本地化字符串。
        /// </summary>
        internal static string Failure_of_total_functional_information_modification {
            get {
                return ResourceManager.GetString("Failure_of_total_functional_information_modification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 冻结 的本地化字符串。
        /// </summary>
        internal static string forbidden {
            get {
                return ResourceManager.GetString("forbidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 功能信息创建失败 的本地化字符串。
        /// </summary>
        internal static string Functional_information_creation_failed {
            get {
                return ResourceManager.GetString("Functional_information_creation_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 功能信息创建成功 的本地化字符串。
        /// </summary>
        internal static string Function_information_to_create_success {
            get {
                return ResourceManager.GetString("Function_information_to_create_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查询充值总额 的本地化字符串。
        /// </summary>
        internal static string function_msg1 {
            get {
                return ResourceManager.GetString("function_msg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查询充值是否成功 的本地化字符串。
        /// </summary>
        internal static string function_msg2 {
            get {
                return ResourceManager.GetString("function_msg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查询钻石数量 的本地化字符串。
        /// </summary>
        internal static string function_msg3 {
            get {
                return ResourceManager.GetString("function_msg3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改钻石数量 的本地化字符串。
        /// </summary>
        internal static string function_msg4 {
            get {
                return ResourceManager.GetString("function_msg4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发送系统公告 的本地化字符串。
        /// </summary>
        internal static string function_msg5 {
            get {
                return ResourceManager.GetString("function_msg5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查询在线人数 的本地化字符串。
        /// </summary>
        internal static string function_msg6 {
            get {
                return ResourceManager.GetString("function_msg6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 充值 的本地化字符串。
        /// </summary>
        internal static string function_msg7 {
            get {
                return ResourceManager.GetString("function_msg7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请求线上房间数量 的本地化字符串。
        /// </summary>
        internal static string function_msg8 {
            get {
                return ResourceManager.GetString("function_msg8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 功能名称 的本地化字符串。
        /// </summary>
        internal static string function_name {
            get {
                return ResourceManager.GetString("function_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始时间 的本地化字符串。
        /// </summary>
        internal static string function_tip1 {
            get {
                return ResourceManager.GetString("function_tip1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 结束时间 的本地化字符串。
        /// </summary>
        internal static string function_tip2 {
            get {
                return ResourceManager.GetString("function_tip2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 订单号 的本地化字符串。
        /// </summary>
        internal static string function_tip3 {
            get {
                return ResourceManager.GetString("function_tip3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发布 的本地化字符串。
        /// </summary>
        internal static string function_tip4 {
            get {
                return ResourceManager.GetString("function_tip4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 功能名称【 的本地化字符串。
        /// </summary>
        internal static string Functio_nname {
            get {
                return ResourceManager.GetString("Functio_nname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 游戏渠道 的本地化字符串。
        /// </summary>
        internal static string Game_channel {
            get {
                return ResourceManager.GetString("Game_channel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 游戏描述 的本地化字符串。
        /// </summary>
        internal static string Game_description {
            get {
                return ResourceManager.GetString("Game_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 游戏ID 的本地化字符串。
        /// </summary>
        internal static string game_ID {
            get {
                return ResourceManager.GetString("game_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 游戏管理 的本地化字符串。
        /// </summary>
        internal static string game_management {
            get {
                return ResourceManager.GetString("game_management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 游戏名称 的本地化字符串。
        /// </summary>
        internal static string game_name {
            get {
                return ResourceManager.GetString("game_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 游戏设置 的本地化字符串。
        /// </summary>
        internal static string game_setting {
            get {
                return ResourceManager.GetString("game_setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 游戏ID【 的本地化字符串。
        /// </summary>
        internal static string Gam_eID {
            get {
                return ResourceManager.GetString("Gam_eID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 钻石数量 的本地化字符串。
        /// </summary>
        internal static string goodsdiamondnum {
            get {
                return ResourceManager.GetString("goodsdiamondnum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 商品Id 的本地化字符串。
        /// </summary>
        internal static string goodsid {
            get {
                return ResourceManager.GetString("goodsid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 商品名称 的本地化字符串。
        /// </summary>
        internal static string goodsname {
            get {
                return ResourceManager.GetString("goodsname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 赠送数量 的本地化字符串。
        /// </summary>
        internal static string goodspresentnum {
            get {
                return ResourceManager.GetString("goodspresentnum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 商品价格 的本地化字符串。
        /// </summary>
        internal static string goodsprice {
            get {
                return ResourceManager.GetString("goodsprice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 折扣率 的本地化字符串。
        /// </summary>
        internal static string goodsrate {
            get {
                return ResourceManager.GetString("goodsrate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 商品添加失败 的本地化字符串。
        /// </summary>
        internal static string goods_add_fail {
            get {
                return ResourceManager.GetString("goods_add_fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 商品添加成功 的本地化字符串。
        /// </summary>
        internal static string goods_add_suc {
            get {
                return ResourceManager.GetString("goods_add_suc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查询 的本地化字符串。
        /// </summary>
        internal static string goods_diamon_num {
            get {
                return ResourceManager.GetString("goods_diamon_num", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 商品修改失败 的本地化字符串。
        /// </summary>
        internal static string goods_edit_fail {
            get {
                return ResourceManager.GetString("goods_edit_fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 商品修改成功 的本地化字符串。
        /// </summary>
        internal static string goods_edit_suc {
            get {
                return ResourceManager.GetString("goods_edit_suc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在树目录中隐藏 的本地化字符串。
        /// </summary>
        internal static string Hide_in_the_tree_directory {
            get {
                return ResourceManager.GetString("Hide_in_the_tree_directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 反选 的本地化字符串。
        /// </summary>
        internal static string inverse {
            get {
                return ResourceManager.GetString("inverse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 跟内部日志查询编号有关 的本地化字符串。
        /// </summary>
        internal static string Is_related_to_the_internal_log_query_number {
            get {
                return ResourceManager.GetString("Is_related_to_the_internal_log_query_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 语言 的本地化字符串。
        /// </summary>
        internal static string language {
            get {
                return ResourceManager.GetString("language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上次登录IP 的本地化字符串。
        /// </summary>
        internal static string last_login_ip {
            get {
                return ResourceManager.GetString("last_login_ip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上次登录时间 的本地化字符串。
        /// </summary>
        internal static string last_login_time {
            get {
                return ResourceManager.GetString("last_login_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 链接 的本地化字符串。
        /// </summary>
        internal static string link {
            get {
                return ResourceManager.GetString("link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登录 的本地化字符串。
        /// </summary>
        internal static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登录信息 的本地化字符串。
        /// </summary>
        internal static string login_information {
            get {
                return ResourceManager.GetString("login_information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 本次登录IP 的本地化字符串。
        /// </summary>
        internal static string Login_IP {
            get {
                return ResourceManager.GetString("Login_IP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 本次登录时间 的本地化字符串。
        /// </summary>
        internal static string login_time {
            get {
                return ResourceManager.GetString("login_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 本月登录总数 的本地化字符串。
        /// </summary>
        internal static string login_timesofthismonth {
            get {
                return ResourceManager.GetString("login_timesofthismonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 总功能名称 的本地化字符串。
        /// </summary>
        internal static string Major_function_name {
            get {
                return ResourceManager.GetString("Major_function_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主要信息标记 的本地化字符串。
        /// </summary>
        internal static string major_information_mark {
            get {
                return ResourceManager.GetString("major_information_mark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 研发管理员以上级别使用 的本地化字符串。
        /// </summary>
        internal static string Managerorabovelevel {
            get {
                return ResourceManager.GetString("Managerorabovelevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 中角色名称【 的本地化字符串。
        /// </summary>
        internal static string Middle_role_name {
            get {
                return ResourceManager.GetString("Middle_role_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改渠道信息 的本地化字符串。
        /// </summary>
        internal static string Modify_channel_information {
            get {
                return ResourceManager.GetString("Modify_channel_information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改 的本地化字符串。
        /// </summary>
        internal static string modify_diamon_num {
            get {
                return ResourceManager.GetString("modify_diamon_num", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改功能信息 的本地化字符串。
        /// </summary>
        internal static string Modify_function_information {
            get {
                return ResourceManager.GetString("Modify_function_information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改游戏创建 的本地化字符串。
        /// </summary>
        internal static string Modify_game_creation {
            get {
                return ResourceManager.GetString("Modify_game_creation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改游戏信息 的本地化字符串。
        /// </summary>
        internal static string Modify_game_info {
            get {
                return ResourceManager.GetString("Modify_game_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改游戏信息成功 的本地化字符串。
        /// </summary>
        internal static string Modify_game_information_successfully {
            get {
                return ResourceManager.GetString("Modify_game_information_successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改总功能信息 的本地化字符串。
        /// </summary>
        internal static string Modify_general_function_information {
            get {
                return ResourceManager.GetString("Modify_general_function_information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改模块 的本地化字符串。
        /// </summary>
        internal static string Modify_module {
            get {
                return ResourceManager.GetString("Modify_module", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改平台信息 的本地化字符串。
        /// </summary>
        internal static string Modify_platform_information {
            get {
                return ResourceManager.GetString("Modify_platform_information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改角色 的本地化字符串。
        /// </summary>
        internal static string Modify_role {
            get {
                return ResourceManager.GetString("Modify_role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改用户 的本地化字符串。
        /// </summary>
        internal static string Modify_user {
            get {
                return ResourceManager.GetString("Modify_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模块地址 的本地化字符串。
        /// </summary>
        internal static string moduleaddress {
            get {
                return ResourceManager.GetString("moduleaddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 子模块创建失败 的本地化字符串。
        /// </summary>
        internal static string Module_creation_failed {
            get {
                return ResourceManager.GetString("Module_creation_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模块功能管理 的本地化字符串。
        /// </summary>
        internal static string module_feature_management {
            get {
                return ResourceManager.GetString("module_feature_management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模块管理 的本地化字符串。
        /// </summary>
        internal static string module_management {
            get {
                return ResourceManager.GetString("module_management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模块修改失败 的本地化字符串。
        /// </summary>
        internal static string Module_modification_failed {
            get {
                return ResourceManager.GetString("Module_modification_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模块修改成功 的本地化字符串。
        /// </summary>
        internal static string Module_modification_success {
            get {
                return ResourceManager.GetString("Module_modification_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 多个IP 请用,分隔 的本地化字符串。
        /// </summary>
        internal static string MultipleIPpleaseuseseparation {
            get {
                return ResourceManager.GetString("MultipleIPpleaseuseseparation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 可多选 的本地化字符串。
        /// </summary>
        internal static string multiselect {
            get {
                return ResourceManager.GetString("multiselect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 姓名 的本地化字符串。
        /// </summary>
        internal static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 中父模块名称【 的本地化字符串。
        /// </summary>
        internal static string Name_of_the_parent_module {
            get {
                return ResourceManager.GetString("Name_of_the_parent_module", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 中总功能名称【 的本地化字符串。
        /// </summary>
        internal static string Name_of_total_function_in {
            get {
                return ResourceManager.GetString("Name_of_total_function_in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 中子模块名称【 的本地化字符串。
        /// </summary>
        internal static string Neutron_module_name {
            get {
                return ResourceManager.GetString("Neutron_module_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 否 的本地化字符串。
        /// </summary>
        internal static string no {
            get {
                return ResourceManager.GetString("no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不能为空 的本地化字符串。
        /// </summary>
        internal static string not_empty {
            get {
                return ResourceManager.GetString("not_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不保存 的本地化字符串。
        /// </summary>
        internal static string not_save {
            get {
                return ResourceManager.GetString("not_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 暂无数据 的本地化字符串。
        /// </summary>
        internal static string No_data {
            get {
                return ResourceManager.GetString("No_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 暂无平台信息 点击进行创建 的本地化字符串。
        /// </summary>
        internal static string No_information_click_create_platform {
            get {
                return ResourceManager.GetString("No_information_click_create_platform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 暂无子模块 的本地化字符串。
        /// </summary>
        internal static string no_sub_module {
            get {
                return ResourceManager.GetString("no_sub_module", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 停用 的本地化字符串。
        /// </summary>
        internal static string Off {
            get {
                return ResourceManager.GetString("Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启用 的本地化字符串。
        /// </summary>
        internal static string On {
            get {
                return ResourceManager.GetString("On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在线人数 的本地化字符串。
        /// </summary>
        internal static string online {
            get {
                return ResourceManager.GetString("online", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 部门 的本地化字符串。
        /// </summary>
        internal static string Onlydepartment {
            get {
                return ResourceManager.GetString("Onlydepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 角色 的本地化字符串。
        /// </summary>
        internal static string OnlyRole {
            get {
                return ResourceManager.GetString("OnlyRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 欢迎 的本地化字符串。
        /// </summary>
        internal static string OnlyWelcome {
            get {
                return ResourceManager.GetString("OnlyWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否启用 的本地化字符串。
        /// </summary>
        internal static string On_Off {
            get {
                return ResourceManager.GetString("On_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作 的本地化字符串。
        /// </summary>
        internal static string operation {
            get {
                return ResourceManager.GetString("operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作类型 的本地化字符串。
        /// </summary>
        internal static string operationtype {
            get {
                return ResourceManager.GetString("operationtype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作内容 的本地化字符串。
        /// </summary>
        internal static string operation_content {
            get {
                return ResourceManager.GetString("operation_content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开户行 的本地化字符串。
        /// </summary>
        internal static string organizeback {
            get {
                return ResourceManager.GetString("organizeback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开户名 的本地化字符串。
        /// </summary>
        internal static string organizebackname {
            get {
                return ResourceManager.GetString("organizebackname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 银行账号 的本地化字符串。
        /// </summary>
        internal static string organizebackno {
            get {
                return ResourceManager.GetString("organizebackno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 联系方式 的本地化字符串。
        /// </summary>
        internal static string organizecontact {
            get {
                return ResourceManager.GetString("organizecontact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 机构id 的本地化字符串。
        /// </summary>
        internal static string organizeid {
            get {
                return ResourceManager.GetString("organizeid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 介绍人 的本地化字符串。
        /// </summary>
        internal static string organizeintroducer {
            get {
                return ResourceManager.GetString("organizeintroducer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 机构名称 的本地化字符串。
        /// </summary>
        internal static string organizename {
            get {
                return ResourceManager.GetString("organizename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 机构号 的本地化字符串。
        /// </summary>
        internal static string organizeno {
            get {
                return ResourceManager.GetString("organizeno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 联系人 的本地化字符串。
        /// </summary>
        internal static string organizepeople {
            get {
                return ResourceManager.GetString("organizepeople", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分成利润 的本地化字符串。
        /// </summary>
        internal static string organizepercent {
            get {
                return ResourceManager.GetString("organizepercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 地区 的本地化字符串。
        /// </summary>
        internal static string organizezone {
            get {
                return ResourceManager.GetString("organizezone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 拥有角色 的本地化字符串。
        /// </summary>
        internal static string owned_roles {
            get {
                return ResourceManager.GetString("owned_roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模块名称 的本地化字符串。
        /// </summary>
        internal static string parentmodulename {
            get {
                return ResourceManager.GetString("parentmodulename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 父模块创建成功 的本地化字符串。
        /// </summary>
        internal static string Parent_module_creates_success {
            get {
                return ResourceManager.GetString("Parent_module_creates_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 父模块名称 的本地化字符串。
        /// </summary>
        internal static string parent_module_name {
            get {
                return ResourceManager.GetString("parent_module_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码 的本地化字符串。
        /// </summary>
        internal static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入6-16位任意包含英文、数字、符号的密码，不能使用，；&apos;等特殊符号 的本地化字符串。
        /// </summary>
        internal static string password_check {
            get {
                return ResourceManager.GetString("password_check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码修改 的本地化字符串。
        /// </summary>
        internal static string Password_modification {
            get {
                return ResourceManager.GetString("Password_modification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 人 的本地化字符串。
        /// </summary>
        internal static string person {
            get {
                return ResourceManager.GetString("person", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 个人信息 的本地化字符串。
        /// </summary>
        internal static string personal_information {
            get {
                return ResourceManager.GetString("personal_information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 电话 的本地化字符串。
        /// </summary>
        internal static string phone_number {
            get {
                return ResourceManager.GetString("phone_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 所属平台 的本地化字符串。
        /// </summary>
        internal static string platform {
            get {
                return ResourceManager.GetString("platform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 平台信息创建失败 的本地化字符串。
        /// </summary>
        internal static string Platform_information_creation_failed {
            get {
                return ResourceManager.GetString("Platform_information_creation_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 平台信息修改失败 的本地化字符串。
        /// </summary>
        internal static string Platform_information_modification_failed {
            get {
                return ResourceManager.GetString("Platform_information_modification_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 平台信息创建成功 的本地化字符串。
        /// </summary>
        internal static string Platform_information_to_create_success {
            get {
                return ResourceManager.GetString("Platform_information_to_create_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 平台管理 的本地化字符串。
        /// </summary>
        internal static string platform_management {
            get {
                return ResourceManager.GetString("platform_management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 平台名称 的本地化字符串。
        /// </summary>
        internal static string platform_name {
            get {
                return ResourceManager.GetString("platform_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 平台排序 的本地化字符串。
        /// </summary>
        internal static string platform_order {
            get {
                return ResourceManager.GetString("platform_order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 平台排序必须为数字 的本地化字符串。
        /// </summary>
        internal static string Platform_ordering_must_be_numeric {
            get {
                return ResourceManager.GetString("Platform_ordering_must_be_numeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 平台图片 的本地化字符串。
        /// </summary>
        internal static string platform_picture {
            get {
                return ResourceManager.GetString("platform_picture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 平台名称【 的本地化字符串。
        /// </summary>
        internal static string Platfor_mname {
            get {
                return ResourceManager.GetString("Platfor_mname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 玩家id 的本地化字符串。
        /// </summary>
        internal static string playerId {
            get {
                return ResourceManager.GetString("playerId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 玩家名 的本地化字符串。
        /// </summary>
        internal static string playnames {
            get {
                return ResourceManager.GetString("playnames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择账号级别 的本地化字符串。
        /// </summary>
        internal static string Pleaseselecttheaccountlevel {
            get {
                return ResourceManager.GetString("Pleaseselecttheaccountlevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入角色名 的本地化字符串。
        /// </summary>
        internal static string Please_enter_a_character_name {
            get {
                return ResourceManager.GetString("Please_enter_a_character_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入功能名称 的本地化字符串。
        /// </summary>
        internal static string Please_enter_a_function_name {
            get {
                return ResourceManager.GetString("Please_enter_a_function_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入模块地址 的本地化字符串。
        /// </summary>
        internal static string Please_enter_a_module_address {
            get {
                return ResourceManager.GetString("Please_enter_a_module_address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入排序数字 的本地化字符串。
        /// </summary>
        internal static string Please_enter_a_sort_number {
            get {
                return ResourceManager.GetString("Please_enter_a_sort_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入用户账号 的本地化字符串。
        /// </summary>
        internal static string Please_enter_a_user_account {
            get {
                return ResourceManager.GetString("Please_enter_a_user_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入用户密码 的本地化字符串。
        /// </summary>
        internal static string Please_enter_a_user_password {
            get {
                return ResourceManager.GetString("Please_enter_a_user_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入模块名称 的本地化字符串。
        /// </summary>
        internal static string Please_enter_the_name_of_the_module {
            get {
                return ResourceManager.GetString("Please_enter_the_name_of_the_module", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入总功能名称 的本地化字符串。
        /// </summary>
        internal static string Please_enter_the_name_of_the_total_function {
            get {
                return ResourceManager.GetString("Please_enter_the_name_of_the_total_function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入必填项 的本地化字符串。
        /// </summary>
        internal static string Please_enter_the_required {
            get {
                return ResourceManager.GetString("Please_enter_the_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入用户姓名 的本地化字符串。
        /// </summary>
        internal static string Please_enter_user_name {
            get {
                return ResourceManager.GetString("Please_enter_user_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请录入必填项 的本地化字符串。
        /// </summary>
        internal static string Please_input_the_required {
            get {
                return ResourceManager.GetString("Please_input_the_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择角色名 的本地化字符串。
        /// </summary>
        internal static string Please_select_a_character_name {
            get {
                return ResourceManager.GetString("Please_select_a_character_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择部门 的本地化字符串。
        /// </summary>
        internal static string Please_select_Department {
            get {
                return ResourceManager.GetString("Please_select_Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择功能名称 的本地化字符串。
        /// </summary>
        internal static string Please_select_the_function_name {
            get {
                return ResourceManager.GetString("Please_select_the_function_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择平台名称 的本地化字符串。
        /// </summary>
        internal static string Please_select_the_platform_name {
            get {
                return ResourceManager.GetString("Please_select_the_platform_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择总功能名称 的本地化字符串。
        /// </summary>
        internal static string Please_select_the_total_function_name {
            get {
                return ResourceManager.GetString("Please_select_the_total_function_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择用户部门 的本地化字符串。
        /// </summary>
        internal static string Please_select_user_department {
            get {
                return ResourceManager.GetString("Please_select_user_department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请上传平台图片 的本地化字符串。
        /// </summary>
        internal static string Please_upload_platform {
            get {
                return ResourceManager.GetString("Please_upload_platform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 注册日期 的本地化字符串。
        /// </summary>
        internal static string registered_date {
            get {
                return ResourceManager.GetString("registered_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 注册ip 的本地化字符串。
        /// </summary>
        internal static string registered_ip {
            get {
                return ResourceManager.GetString("registered_ip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 备注 的本地化字符串。
        /// </summary>
        internal static string Remarks {
            get {
                return ResourceManager.GetString("Remarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重置 的本地化字符串。
        /// </summary>
        internal static string reset {
            get {
                return ResourceManager.GetString("reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 返回 的本地化字符串。
        /// </summary>
        internal static string Return {
            get {
                return ResourceManager.GetString("Return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 返回角色列表 的本地化字符串。
        /// </summary>
        internal static string returnrolelist {
            get {
                return ResourceManager.GetString("returnrolelist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重新上传 的本地化字符串。
        /// </summary>
        internal static string Re_upload {
            get {
                return ResourceManager.GetString("Re_upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户角色 的本地化字符串。
        /// </summary>
        internal static string role {
            get {
                return ResourceManager.GetString("role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 角色信息修改成功 的本地化字符串。
        /// </summary>
        internal static string Role_information_change_success {
            get {
                return ResourceManager.GetString("Role_information_change_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 角色信息创建失败 的本地化字符串。
        /// </summary>
        internal static string Role_information_creation_failed {
            get {
                return ResourceManager.GetString("Role_information_creation_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 角色信息创建成功 的本地化字符串。
        /// </summary>
        internal static string Role_information_creation_success {
            get {
                return ResourceManager.GetString("Role_information_creation_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 角色信息修改失败 的本地化字符串。
        /// </summary>
        internal static string Role_information_modification_failed {
            get {
                return ResourceManager.GetString("Role_information_modification_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 角色管理 的本地化字符串。
        /// </summary>
        internal static string Role_management {
            get {
                return ResourceManager.GetString("Role_management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 角色名 的本地化字符串。
        /// </summary>
        internal static string role_name {
            get {
                return ResourceManager.GetString("role_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 房间号 的本地化字符串。
        /// </summary>
        internal static string roomno {
            get {
                return ResourceManager.GetString("roomno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存一天 的本地化字符串。
        /// </summary>
        internal static string save_the_day {
            get {
                return ResourceManager.GetString("save_the_day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存一月 的本地化字符串。
        /// </summary>
        internal static string save_the_month {
            get {
                return ResourceManager.GetString("save_the_month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存一年 的本地化字符串。
        /// </summary>
        internal static string save_the_year {
            get {
                return ResourceManager.GetString("save_the_year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 搜索 的本地化字符串。
        /// </summary>
        internal static string search {
            get {
                return ResourceManager.GetString("search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择 的本地化字符串。
        /// </summary>
        internal static string select {
            get {
                return ResourceManager.GetString("select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 仿真 的本地化字符串。
        /// </summary>
        internal static string simulation {
            get {
                return ResourceManager.GetString("simulation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 排序 的本地化字符串。
        /// </summary>
        internal static string sort {
            get {
                return ResourceManager.GetString("sort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 sql导出数据 的本地化字符串。
        /// </summary>
        internal static string SQL_export_data {
            get {
                return ResourceManager.GetString("SQL_export_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SQL查询 的本地化字符串。
        /// </summary>
        internal static string SQL_search {
            get {
                return ResourceManager.GetString("SQL_search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始时间 的本地化字符串。
        /// </summary>
        internal static string starting_time {
            get {
                return ResourceManager.GetString("starting_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 州/省 的本地化字符串。
        /// </summary>
        internal static string state {
            get {
                return ResourceManager.GetString("state", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户状态 的本地化字符串。
        /// </summary>
        internal static string status {
            get {
                return ResourceManager.GetString("status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提示：为了账号的安全，如果上面的登录情况不正常，建议您马上 的本地化字符串。
        /// </summary>
        internal static string String16 {
            get {
                return ResourceManager.GetString("String16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 子模块 的本地化字符串。
        /// </summary>
        internal static string submodule {
            get {
                return ResourceManager.GetString("submodule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 子模块名称 的本地化字符串。
        /// </summary>
        internal static string submodule_name {
            get {
                return ResourceManager.GetString("submodule_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 子模块创建成功 的本地化字符串。
        /// </summary>
        internal static string Sub_module_to_create_success {
            get {
                return ResourceManager.GetString("Sub_module_to_create_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 平台信息修改成功 的本地化字符串。
        /// </summary>
        internal static string Successful_platform_information_modification {
            get {
                return ResourceManager.GetString("Successful_platform_information_modification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成功,创建 的本地化字符串。
        /// </summary>
        internal static string Success_create {
            get {
                return ResourceManager.GetString("Success_create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 功能信息修改成功 的本地化字符串。
        /// </summary>
        internal static string Success_of_functional_information_modification {
            get {
                return ResourceManager.GetString("Success_of_functional_information_modification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户信息修改成功 的本地化字符串。
        /// </summary>
        internal static string Success_of_user_information_modification {
            get {
                return ResourceManager.GetString("Success_of_user_information_modification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 切换平台 的本地化字符串。
        /// </summary>
        internal static string switch_platform {
            get {
                return ResourceManager.GetString("switch_platform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统应用 的本地化字符串。
        /// </summary>
        internal static string system_application {
            get {
                return ResourceManager.GetString("system_application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 目标账号 的本地化字符串。
        /// </summary>
        internal static string targetaccount {
            get {
                return ResourceManager.GetString("targetaccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 暂无角色信息 点击进行创建 的本地化字符串。
        /// </summary>
        internal static string TheroleofinformationandclickCreate {
            get {
                return ResourceManager.GetString("TheroleofinformationandclickCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 暂无功能信息 点击进行创建 的本地化字符串。
        /// </summary>
        internal static string The_function_of_information_and_click_Create {
            get {
                return ResourceManager.GetString("The_function_of_information_and_click_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 暂无总功能信息 点击进行创建 的本地化字符串。
        /// </summary>
        internal static string The_general_information_and_click_the_create_function {
            get {
                return ResourceManager.GetString("The_general_information_and_click_the_create_function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 总功能信息修改成功 的本地化字符串。
        /// </summary>
        internal static string The_success_of_total_functional_information_modification {
            get {
                return ResourceManager.GetString("The_success_of_total_functional_information_modification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 次 的本地化字符串。
        /// </summary>
        internal static string time {
            get {
                return ResourceManager.GetString("time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 亲, 您的帐号已经设定登录IP限制，请在常用IP下登录! 的本地化字符串。
        /// </summary>
        internal static string Tip_AccountIpLimit {
            get {
                return ResourceManager.GetString("Tip_AccountIpLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 验证码错误！ 的本地化字符串。
        /// </summary>
        internal static string Tip_CodeError {
            get {
                return ResourceManager.GetString("Tip_CodeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 内容 的本地化字符串。
        /// </summary>
        internal static string tip_content {
            get {
                return ResourceManager.GetString("tip_content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除成功 的本地化字符串。
        /// </summary>
        internal static string tip_delete_success {
            get {
                return ResourceManager.GetString("tip_delete_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 （失败）：复制权限： 的本地化字符串。
        /// </summary>
        internal static string Tip_FaileCopy {
            get {
                return ResourceManager.GetString("Tip_FaileCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统异常，请重新登录! 的本地化字符串。
        /// </summary>
        internal static string Tip_LoginError {
            get {
                return ResourceManager.GetString("Tip_LoginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不能给自己账号中复制或转移 的本地化字符串。
        /// </summary>
        internal static string Tip_not_OptMyself {
            get {
                return ResourceManager.GetString("Tip_not_OptMyself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择一条记录进行修改 的本地化字符串。
        /// </summary>
        internal static string tip_one_modify {
            get {
                return ResourceManager.GetString("tip_one_modify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请至少选择一条记录进行删除 的本地化字符串。
        /// </summary>
        internal static string tip_only_delete {
            get {
                return ResourceManager.GetString("tip_only_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 一次只能修改一条记录 的本地化字符串。
        /// </summary>
        internal static string tip_only_modify {
            get {
                return ResourceManager.GetString("tip_only_modify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您确定要进入 的本地化字符串。
        /// </summary>
        internal static string tip_sure_enter {
            get {
                return ResourceManager.GetString("tip_sure_enter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 （成功）：复制权限： 的本地化字符串。
        /// </summary>
        internal static string Tip_SuscessCopy {
            get {
                return ResourceManager.GetString("Tip_SuscessCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 亲, 您的帐号还没有激活,请联系管理员激活! 的本地化字符串。
        /// </summary>
        internal static string Tip_UserAccountActivation {
            get {
                return ResourceManager.GetString("Tip_UserAccountActivation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 亲, 您的账户已经被冻结请联系管理员或24小时后自动解冻 解冻时间为 的本地化字符串。
        /// </summary>
        internal static string Tip_UserAccountThaw {
            get {
                return ResourceManager.GetString("Tip_UserAccountThaw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 总功能信息创建失败 的本地化字符串。
        /// </summary>
        internal static string Total_function_information_creation_failed {
            get {
                return ResourceManager.GetString("Total_function_information_creation_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 总功能信息创建成功 的本地化字符串。
        /// </summary>
        internal static string Total_function_information_creation_success {
            get {
                return ResourceManager.GetString("Total_function_information_creation_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 转移 的本地化字符串。
        /// </summary>
        internal static string transfer {
            get {
                return ResourceManager.GetString("transfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 被转移用户账号会被停用，角色会被清空，慎用 的本地化字符串。
        /// </summary>
        internal static string Transferuseraccountwithcaution {
            get {
                return ResourceManager.GetString("Transferuseraccountwithcaution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 转移权限 的本地化字符串。
        /// </summary>
        internal static string transfer_authority {
            get {
                return ResourceManager.GetString("transfer_authority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改 的本地化字符串。
        /// </summary>
        internal static string update {
            get {
                return ResourceManager.GetString("update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户部门 的本地化字符串。
        /// </summary>
        internal static string userdepartment {
            get {
                return ResourceManager.GetString("userdepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户名 的本地化字符串。
        /// </summary>
        internal static string username {
            get {
                return ResourceManager.GetString("username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户不存在 的本地化字符串。
        /// </summary>
        internal static string usernotexist {
            get {
                return ResourceManager.GetString("usernotexist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上级机构 的本地化字符串。
        /// </summary>
        internal static string userparentid {
            get {
                return ResourceManager.GetString("userparentid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 手机号码 的本地化字符串。
        /// </summary>
        internal static string userphone {
            get {
                return ResourceManager.GetString("userphone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户角色 的本地化字符串。
        /// </summary>
        internal static string userrole {
            get {
                return ResourceManager.GetString("userrole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 地区 的本地化字符串。
        /// </summary>
        internal static string userzone {
            get {
                return ResourceManager.GetString("userzone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户账号 的本地化字符串。
        /// </summary>
        internal static string user_account {
            get {
                return ResourceManager.GetString("user_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户账号【 的本地化字符串。
        /// </summary>
        internal static string User_account1 {
            get {
                return ResourceManager.GetString("User_account1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户信息创建失败 的本地化字符串。
        /// </summary>
        internal static string User_information_creation_failed {
            get {
                return ResourceManager.GetString("User_information_creation_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户信息创建成功 的本地化字符串。
        /// </summary>
        internal static string User_information_creation_success {
            get {
                return ResourceManager.GetString("User_information_creation_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户信息修改失败 的本地化字符串。
        /// </summary>
        internal static string User_information_modification_failed {
            get {
                return ResourceManager.GetString("User_information_modification_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户信息查询 的本地化字符串。
        /// </summary>
        internal static string user_information_search {
            get {
                return ResourceManager.GetString("user_information_search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户管理 的本地化字符串。
        /// </summary>
        internal static string user_management {
            get {
                return ResourceManager.GetString("user_management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户密码 的本地化字符串。
        /// </summary>
        internal static string user_password {
            get {
                return ResourceManager.GetString("user_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户角色管理 的本地化字符串。
        /// </summary>
        internal static string user_role_management {
            get {
                return ResourceManager.GetString("user_role_management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户类型 的本地化字符串。
        /// </summary>
        internal static string user_type {
            get {
                return ResourceManager.GetString("user_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户登录 的本地化字符串。
        /// </summary>
        internal static string use_login {
            get {
                return ResourceManager.GetString("use_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 验证 的本地化字符串。
        /// </summary>
        internal static string verification {
            get {
                return ResourceManager.GetString("verification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 验证码 的本地化字符串。
        /// </summary>
        internal static string verification_code {
            get {
                return ResourceManager.GetString("verification_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 验证成功 的本地化字符串。
        /// </summary>
        internal static string verification_successful {
            get {
                return ResourceManager.GetString("verification_successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 天气预报 的本地化字符串。
        /// </summary>
        internal static string weather_forecast {
            get {
                return ResourceManager.GetString("weather_forecast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 欢迎首页 的本地化字符串。
        /// </summary>
        internal static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否在树目录中显示 的本地化字符串。
        /// </summary>
        internal static string Whether_to_display_in_the_tree_directory {
            get {
                return ResourceManager.GetString("Whether_to_display_in_the_tree_directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是 的本地化字符串。
        /// </summary>
        internal static string yes {
            get {
                return ResourceManager.GetString("yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 邮编 的本地化字符串。
        /// </summary>
        internal static string zip_code {
            get {
                return ResourceManager.GetString("zip_code", resourceCulture);
            }
        }
    }
}
